### ISSUE TITLE
Add Admin screen with ability to optionally configure with precinct, and additionally party.

### ISSUE THREAD

**Issue by benadida** [votingworks/bas#39]
@mcchilders says:
> for primaries, the R & D ballots need to be separated on vxencode so they can’t give the wrong one (primaries in MS have two check-in stations per polling place, one for each party, that seems to be unique to ms)

---

BAS should be configurable by a clerk/admin such that:
- it is optionally locked into a single precinct and can only encode that precinct's ballot styles
- it is optionally locked into a single party and can only encode that party's ballot styles

Configuring for *both* is the likely use case, especially in primaries, where different parties will check in at different desks, each with a BAS.

**Comment by beausmith** [comment]
I think this title means "Ability to configure a VxEncode for a single precinct". Is this correct?

But the "party lock-in" part I'm confused about. What does this mean? Is this a separate task?

**Comment by benadida** [comment]
@beausmith I've updated the issue description to clear things up. If you prefer to split into two tickets, that's fine, though I suspect that it's all happening in one set of configuration screens.
